version: '3'

volumes:
  media:

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=0
    volumes:
      - media:/app/media

  gateway:
    container_name: proxy
    build: ./gateway
    volumes:
      - media:/media/
    ports:
      - "80:80"
